services:
  - type: web
    name: matrischol
    env: python
    plan: free
    autoDeploy: true
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn matrischol_project.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: matrischol_project.settings
      - key: PYTHON_VERSION
        value: 3.12.7